### ISSUE TITLE
WebSocket disconnects after some time, and requires Homebridge restart to reconnect

### ISSUE THREAD

**Issue by valeriansaliou** [rsauget/homebridge-flexom#111] opened 2023-02-21 14:57 UTC
Hello there!

Overall Homebridge-Flexom is working great :) I've noticed a tiny issue w/ the WebSocket input channel, allowing to update HAP state whenever eg. a physical light switch is powered on or off, in real-time. This works just fine when Homebridge was just restarted, although after some time (days? network loss? anything else) it loses connection to the WS server and never reconnects.

When this happens, controls from HAP still work eg. I can hit Hemis API and enable/disable lights or control roller shutters, but physical actions are not reflected in real-time anymore in HAP. Restarting Homebridge will force the Homebridge-Flexom plugin to restart, which will reconnect to WebSocket, and fix the issue, until this happens again.

**Comment by GrimalDev** [comment] 2023-02-25 21:24
Hello!
Nice to know I am not the only one who it happens some times...

**Comment by rsauget** [comment] 2023-03-08 18:39
Hi @valeriansaliou, thanks for the report!
This is a duplicate of #108, so I'm gonna close it, feel free to follow up there!

**Closed** 2023-03-08 18:39 UTC
Labels: bug
